from JuegoPrincipal.TTabuleiro import TTabuleiro
from JuegoPrincipal.ECor import ECOR

tabuleiro = TTabuleiro()
tabuleiro.imprimirTabuleiro()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERMELHO)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.PRETO)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERDE)
tabuleiro.printarAsCores()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERMELHO)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.PRETO)
tabuleiro.printarAsCores()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERMELHO)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERDE)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERMELHO)
tabuleiro.printarAsCores()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.BRANCO)
tabuleiro.printarAsCores()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0,ECOR.VERMELHO)
tabuleiro.imprimirTabuleiroValores()