from TTabuleiro import TTabuleiro

tabuleiro = TTabuleiro()
tabuleiro.imprimirTabuleiro()
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()
tabuleiro.clicarEnUnValor(0,0)
tabuleiro.imprimirTabuleiroValores()